### ISSUE TITLE
Some dependency upgrade caused boot-time errors

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/tanqueReact#219]
I think this means that some code actually wasn't compatible with an upgrade, and/or the build provides false positives.
![2017-10-17-112901_875x325_scrot](https://user-images.githubusercontent.com/199018/31673908-65217976-b32e-11e7-98a3-f672f1bfbea3.png)

**Comment by tv1ster** [comment]
@NullVoxPopuli  remove all '^' versions from package.json and run 'npm i'. That should fix an issue.

**Comment by ecollis6** [comment]
You can probably close this now... there were a few more dependency warnings, but I think it's going to be hard to use react + redux latest and the libraries that were complaining

**Comment by NullVoxPopuli** [comment]
yup, https://nullvoxpopuli.github.io/tanqueReact works again. thanks!
